/**
 * Single source of truth for every sourceType value stamped in this codebase.
 *
 * RULES — READ BEFORE EDITING
 * ─────────────────────────────────────────────────────────────────────────────
 * 1. These strings are DATA, not code. They are already written into historical
 *    journalEntries rows in production databases. Do NOT rename, normalise,
 *    prefix, or "tidy" any value here. If a name looks inconsistent (see note
 *    below), leave it — renaming is a data migration, not a refactor.
 *
 * 2. Every file that stamps a sourceType must import from this module.
 *    Every file that reads one must import from this module.
 *    No hand-typed sourceType string literals anywhere in convex/.
 *
 * 3. To add a new source type: add a constant here first, then use it at the
 *    stamp site. Never stamp a value that does not have a constant here.
 *
 * 4. _reversal variants are NOT listed here. lib/ledger.ts:239 constructs them
 *    at runtime as `${sourceType}_reversal`. classifyEntry() in dayBook.ts
 *    strips that suffix before lookup, so they classify identically to their
 *    base type. They do occur in the database; they are intentionally absent
 *    from this map.
 *
 * NAMING NOTE
 * ─────────────────────────────────────────────────────────────────────────────
 * "payment" (customer pays AR) vs "bill_payment" (we pay AP) vs "bank_payment"
 * (ad-hoc bank outflow) are three distinct concepts with inconsistent names.
 * "bank_payment" is arguably closer to "bill_payment" semantically, and
 * "payment" arguably deserves a "customer_" prefix. These inconsistencies are
 * left unchanged because the values exist in historical rows.
 *
 * COUNT: 34 distinct values.
 */

// ─── Sales & Invoices ─────────────────────────────────────────────────────────

/** Revenue recognition entry for a credit invoice.
 *  Stamps: convex/invoicing.ts */
export const INVOICE_SALE_SOURCE = "invoice_sale";

/** Paired COGS debit generated by the same invoice posting.
 *  Stamps: convex/invoicing.ts */
export const INVOICE_COGS_SOURCE = "invoice_cogs";

/** POS / direct (point-of-sale) sale revenue entry.
 *  Stamps: convex/sales.ts */
export const SALE_SOURCE = "sale";

/** Paired COGS debit generated by the same POS sale posting.
 *  Stamps: convex/sales.ts */
export const SALE_COGS_SOURCE = "sale_cogs";

/** Amount correction on a posted sale.
 *  Stamps: convex/sales.ts */
export const SALE_ADJUSTMENT_SOURCE = "sale_adjustment";

/** Credit memo issued to a customer (reduces AR and revenue).
 *  Stamps: convex/invoicing.ts */
export const CREDIT_MEMO_SOURCE = "credit_memo";

/** Inventory restock reversal of COGS on a customer return.
 *  Stamps: convex/returns.ts */
export const RETURN_RESTOCK_SOURCE = "return_restock";

// ─── Customer Receipts ───────────────────────────────────────────────────────

/** Customer pays an invoice (Dr Bank / Cr AR).
 *  Stamps: convex/invoicing.ts, convex/payments.ts */
export const PAYMENT_SOURCE = "payment";

/** Customer prepays before an invoice exists (Dr Bank / Cr Advance Liability).
 *  Stamps: convex/advancePayments.ts */
export const CUSTOMER_ADVANCE_SOURCE = "customer_advance";

/** Customer advance applied against an invoice (Dr Advance Liability / Cr AR).
 *  Stamps: convex/advancePayments.ts */
export const ADVANCE_SETTLEMENT_SOURCE = "advance_settlement";

/** Customer deposit received (Dr Bank / Cr Deposit Liability).
 *  Stamps: convex/customerDeposits.ts */
export const CUSTOMER_DEPOSIT_SOURCE = "customer_deposit";

/** Customer deposit applied to an invoice (Dr Deposit Liability / Cr AR).
 *  Stamps: convex/customerDeposits.ts */
export const DEPOSIT_APPLICATION_SOURCE = "deposit_application";

/** Cash refund of a customer return (Cr Bank / Dr AR or Revenue).
 *  Stamps: convex/returns.ts */
export const RETURN_REFUND_SOURCE = "return_refund";

/** Cash refund of a customer advance (Cr Bank / Dr Advance Liability).
 *  Stamps: convex/advancePayments.ts */
export const ADVANCE_REFUND_SOURCE = "advance_refund";

/** Cash refund of a customer deposit (Cr Bank / Dr Deposit Liability).
 *  Stamps: convex/customerDeposits.ts */
export const CUSTOMER_DEPOSIT_REFUND_SOURCE = "customer_deposit_refund";

// ─── Purchases & Bills ───────────────────────────────────────────────────────

/** Vendor bill posted (Dr Expense/Inventory / Cr AP).
 *  Stamps: convex/lib/payablesPosting.ts */
export const BILL_SOURCE = "bill";

/** Goods received into inventory (Dr Inventory / Cr AP or GRNI).
 *  Stamps: convex/lib/payablesPosting.ts */
export const GOODS_RECEIPT_SOURCE = "goods_receipt";

// ─── Vendor Payments ─────────────────────────────────────────────────────────

/** Bill payment sent to vendor (Dr AP / Cr Bank).
 *  Stamps: convex/lib/payablesPosting.ts */
export const BILL_PAYMENT_SOURCE = "bill_payment";

/** Money advanced to a vendor before a bill exists (Dr Vendor Prepaid / Cr Bank).
 *  Stamps: convex/lib/payablesPosting.ts */
export const VENDOR_ADVANCE_SOURCE = "vendor_advance";

/** Split bill payment — one journal entry covers multiple bills.
 *  sourceId is the journalEntryId. Allocations tracked in billPaymentAllocations.
 *  Stamps: convex/billPayments.ts */
export const SPLIT_BILL_PAYMENT_SOURCE = "split_bill_payment";

/** Expense recorded and posted to the ledger (Dr Expense category account / Cr Accrued Expenses Payable).
 *  sourceId is the expense record id.
 *  Stamps: convex/vendors.ts */
export const EXPENSE_POSTING_SOURCE = "expense_posting";

// ─── Banking ─────────────────────────────────────────────────────────────────

/** Check drawn on a bank account (Dr Expense / Cr Bank).
 *  sourceId is NOT set; reference is on the journal entry itself.
 *  Stamps: convex/bankingOperations.ts */
export const BANK_CHECK_SOURCE = "bank_check";

/** Ad-hoc bank fee or direct expense (Dr Expense / Cr Bank).
 *  sourceId is NOT set; reference is on the journal entry itself.
 *  Stamps: convex/bankingOperations.ts */
export const BANK_EXPENSE_SOURCE = "bank_expense";

/** Petty cash disbursement (Dr Expense / Cr Petty Cash).
 *  sourceId is NOT set; reference is on the journal entry itself.
 *  Stamps: convex/bankingOperations.ts */
export const PETTY_CASH_EXPENSE_SOURCE = "petty_cash_expense";

/** Generic payment from a bank account not linked to a bill (Dr Expense / Cr Bank).
 *  sourceId is NOT set; reference is on the journal entry itself.
 *  Stamps: convex/bankingOperations.ts */
export const BANK_PAYMENT_SOURCE = "bank_payment";

/** Petty cash float replenishment (Dr Petty Cash / Cr Bank).
 *  sourceId is NOT set; reference is on the journal entry itself.
 *  Stamps: convex/bankingOperations.ts */
export const PETTY_CASH_REPLENISH_SOURCE = "petty_cash_replenish";

/** Bank-to-bank transfer (Dr To-Account / Cr From-Account).
 *  sourceId is NOT set; reference is on the journal entry itself.
 *  Stamps: convex/bankingOperations.ts */
export const BANK_TRANSFER_SOURCE = "bank_transfer";

/** Manual bank balance correction.
 *  Stamps: convex/banking.ts */
export const BANK_ADJUSTMENT_SOURCE = "bank_adjustment";

/** Imported bank statement line.
 *  Stamps: convex/banking.ts */
export const BANK_IMPORT_SOURCE = "bank_import";

// ─── Payroll ─────────────────────────────────────────────────────────────────

/** Payroll run approved — salary expense accrual (Dr Salaries & Wages / Cr Salaries Payable + SI Payable + Payroll Deductions Payable).
 *  Stamps: convex/lib/payrollPosting.ts */
export const PAYROLL_ACCRUAL_SOURCE = "payroll_accrual";

/** Payroll run approved — employer social-insurance cost (Dr Employer SI Expense / Cr SI Payable).
 *  Stamps: convex/lib/payrollPosting.ts */
export const PAYROLL_EMPLOYER_SI_SOURCE = "payroll_employer_si";

/** Payroll run paid — liability clearance (Dr Salaries Payable / Cr Bank/Cash).
 *  Stamps: convex/lib/payrollPosting.ts */
export const PAYROLL_PAYMENT_SOURCE = "payroll_payment";

/** Period-end end-of-service gratuity accrual (Dr EOS Expense / Cr EOS Benefits Payable).
 *  Stamps: convex/lib/payrollPosting.ts */
export const GRATUITY_ACCRUAL_SOURCE = "gratuity_accrual";

/** Gratuity paid at termination (Dr EOS Benefits Payable / Cr Bank; Dr or Cr EOS Expense for delta).
 *  Stamps: convex/lib/payrollPosting.ts */
export const GRATUITY_PAYMENT_SOURCE = "gratuity_payment";

/** Asset depreciation journal entry (Dr Depreciation Expense / Cr Accumulated Depreciation).
 *  sourceId = assetId + "-" + yearMonth; Stamps: convex/depreciation.ts */
export const DEPRECIATION_SOURCE = "depreciation";

/** Vehicle purchase cost (Dr Vehicles fixed_asset / Cr Accounts Payable).
 *  sourceId = vehicle._id; Stamps: convex/vehicles.ts */
export const VEHICLE_PURCHASE_SOURCE = "vehicle_purchase";

/** Asset purchase cost (Dr Fixed Asset / Cr Accounts Payable).
 *  sourceId = asset._id; Stamps: convex/assets.ts */
export const ASSET_PURCHASE_SOURCE = "asset_purchase";

/** Asset disposal/sale (removes asset cost, removes accumulated depreciation,
 *  records sale proceeds, books gain or loss on disposal).
 *  sourceId = asset._id; Stamps: convex/assets.ts */
export const ASSET_DISPOSAL_SOURCE = "asset_disposal";

// ─── Fleet / Vehicle ─────────────────────────────────────────────────────────

/** Vehicle fuel log (Dr Vehicle Fuel Expense / Cr Accounts Payable or Bank).
 *  sourceId = fuelLog._id; Stamps: convex/vehicles.ts */
export const FUEL_LOG_SOURCE = "fuel_log";

/** Vehicle maintenance/service log (Dr Vehicle Maintenance Expense / Cr Accounts Payable or Bank).
 *  sourceId = maintenanceLog._id; Stamps: convex/vehicles.ts */
export const MAINTENANCE_LOG_SOURCE = "maintenance_log";

// ─── Manual Journal Entries (deliberate fallback) ────────────────────────────
//
// These two source types are intentionally NOT in the SOURCE_TYPE_TO_GROUP map
// in dayBook.ts. They fall to groupIndex === -1 and land in "Manual Journal
// Entries". They are listed here so their values are still constants, not
// hand-typed strings, and so the intent is documented in one place.

/** Year-end closing entry (income summary to retained earnings).
 *  Stamps: convex/accounting.ts */
export const YEAR_END_CLOSE_SOURCE = "year_end_close";

/** One-time cutover opening-balance snapshot entry.
 *  Stamps: convex/reconcileOpeningBalances.ts */
export const OPENING_BALANCES_SOURCE = "opening_balances";

/** Opening stock entered when a product is created
 *  (Dr Inventory / Cr Opening Balance Equity). One entry per product.
 *  Deliberately separate from OPENING_BALANCES_SOURCE: that one marks the
 *  single company-wide cutover and reconcileOpeningBalances.ts refuses to run
 *  twice if it finds it.
 *  sourceId = product._id; Stamps: convex/products.ts */
export const PRODUCT_OPENING_STOCK_SOURCE = "product_opening_stock";

/**
 * The set of source types that deliberately fall through to "Manual Journal
 * Entries" in the Day Book. Not in SOURCE_TYPE_TO_GROUP by design.
 */
/** Customer opening balance (Dr Accounts Receivable / Cr Opening Balance Equity).
 *  Posted with an "opening balance" invoice so it can be aged, reminded and
 *  paid like any receivable. sourceId = invoice._id; Stamps: convex/sales.ts */
export const CUSTOMER_OPENING_BALANCE_SOURCE = "customer_opening_balance";

/** Vendor opening balance (Dr Opening Balance Equity / Cr Accounts Payable).
 *  Posted with an "opening balance" bill so it can be paid like any bill.
 *  sourceId = bill._id; Stamps: convex/vendors.ts */
export const VENDOR_OPENING_BALANCE_SOURCE = "vendor_opening_balance";

/** Stock quantity changed by hand — set level, manual stock in/out, cycle
 *  count (Dr/Cr Inventory against Inventory Adjustments, at average cost).
 *  sourceId = stockMovement._id; Stamps: convex/lib/inventoryPosting.ts */
export const STOCK_ADJUSTMENT_SOURCE = "stock_adjustment";

export const MANUAL_SOURCE_TYPES: ReadonlySet<string> = new Set([
  YEAR_END_CLOSE_SOURCE,
  OPENING_BALANCES_SOURCE,
  PRODUCT_OPENING_STOCK_SOURCE,
  CUSTOMER_OPENING_BALANCE_SOURCE,
  VENDOR_OPENING_BALANCE_SOURCE,
  STOCK_ADJUSTMENT_SOURCE,
]);

// ─── Loans ───────────────────────────────────────────────────────────────────

/** Loan disbursement (Dr Bank or Loan Receivable / Cr Loan Payable or Bank).
 *  sourceId = loan._id; Stamps: convex/loans.ts */
export const LOAN_DISBURSEMENT_SOURCE = "loan_disbursement";

/** Loan repayment installment (Dr Loan Liability + Interest Expense / Cr Bank).
 *  sourceId = loanPayment._id; Stamps: convex/loans.ts */
export const LOAN_REPAYMENT_SOURCE = "loan_repayment";

// ─── Employee Salary Advances ────────────────────────────────────────────────

/** Employee salary advance issued (Dr Employee Advances / Cr Bank/Cash).
 *  sourceId = salaryAdvance._id; Stamps: convex/salaryAdvances.ts */
export const SALARY_ADVANCE_SOURCE = "salary_advance";

/** Salary advance deduction from payslip (Dr Salaries Payable / Cr Employee Advances).
 *  sourceId = salaryAdvance._id; Stamps: convex/salaryAdvances.ts */
export const SALARY_ADVANCE_DEDUCTION_SOURCE = "salary_advance_deduction";

// ─── Bad Debts ───────────────────────────────────────────────────────────────

/** Bad debt write-off: Dr Bad Debt Expense / Cr Accounts Receivable.
 *  NOT a credit note — never merge with CREDIT_MEMO_SOURCE.
 *  A credit note means the sale was wrong; a write-off means the sale was right
 *  and the money did not arrive. Separate sourceType keeps them distinct in the
 *  Day Book, P&L, and audit trail.
 *  sourceId = badDebtWriteOffs._id; Stamps: convex/invoicing.ts */
export const BAD_DEBT_WRITE_OFF_SOURCE = "bad_debt_write_off";

/** Bad debt recovery: Dr Accounts Receivable / Cr Bad Debt Expense (reversal).
 *  sourceId = badDebtWriteOffs._id; Stamps: convex/invoicing.ts */
export const BAD_DEBT_RECOVERY_SOURCE = "bad_debt_recovery";
