// Help data structure - maps route paths to guide keys for context-sensitive help
export const ROUTE_TO_GUIDE: Record<string, string> = {
  "/dashboard": "dashboard",
  "/sales": "sales",
  "/pos": "pos",
  "/products": "products",
  "/inventory": "inventory",
  "/warehouses": "products",
  "/accounting": "accounting",
  "/banking": "banking",
  "/invoicing": "invoicing",
  "/purchasing": "purchasing",
  "/advanced-inventory": "advancedInventory",
  "/pricing": "pricing",
  "/payroll": "payroll",
  "/projects": "projects",
  "/communications": "communications",
  "/security": "security",
  "/reports": "reports",
  "/data": "data",
  "/monitoring": "monitoring",
  "/company-profile": "companyProfile",
  "/tax": "tax",
  "/budget": "budget",
  "/claims": "claims",
  "/crm": "crm",
  "/alerts": "alerts",
  "/branches": "branches",
  "/warranties": "warranties",
  "/loyalty": "loyalty",
};

export const GUIDE_KEYS = [
  "gettingStarted",
  "dashboard",
  "sales",
  "pos",
  "products",
  "inventory",
  "accounting",
  "banking",
  "invoicing",
  "deliveryNotes",
  "purchasing",
  "advancedInventory",
  "pricing",
  "payroll",
  "projects",
  "communications",
  "security",
  "reports",
  "data",
  "monitoring",
  "companyProfile",
  "tax",
  "budget",
  "claims",
  "crm",
  "alerts",
  "branches",
  "warranties",
  "loyalty",
] as const;

export type GuideKey = (typeof GUIDE_KEYS)[number];

export const TUTORIAL_KEYS = [
  "first_sale",
  "setup_accounting",
  "create_invoice",
  "manage_payroll",
  "inventory_setup",
  "import_data",
  "setup_company",
  "create_delivery",
  "run_pos",
] as const;

export type TutorialKey = (typeof TUTORIAL_KEYS)[number];

export const FAQ_KEYS = [
  "how_reset_password",
  "how_add_user",
  "how_backup_data",
  "how_change_language",
  "how_generate_barcode",
  "how_create_role",
  "how_reconcile_bank",
  "how_track_expenses",
  "how_run_reports",
  "how_use_pos",
  "how_delivery_note",
  "how_tax_setup",
  "how_loyalty_program",
  "how_multi_branch",
] as const;

export type FaqKey = (typeof FAQ_KEYS)[number];

// Category groupings for guides
export const GUIDE_CATEGORIES: Record<string, GuideKey[]> = {
  "help.categories.getting_started": ["gettingStarted", "companyProfile"],
  "help.categories.sales": ["sales", "pos", "deliveryNotes"],
  "help.categories.products": ["products", "inventory", "advancedInventory"],
  "help.categories.accounting": ["accounting", "banking", "invoicing", "pricing", "tax", "budget"],
  "help.categories.hr": ["payroll", "projects", "claims"],
  "help.categories.purchasing": ["purchasing"],
  "help.categories.crm": ["crm", "communications", "alerts", "loyalty"],
  "help.categories.operations": ["branches", "warranties", "monitoring"],
  "help.categories.reports": ["reports", "data"],
  "help.categories.settings": ["security"],
};

// Estimated reading time per guide (minutes)
export const GUIDE_READ_TIMES: Record<GuideKey, number> = {
  gettingStarted: 5,
  dashboard: 2,
  sales: 3,
  pos: 3,
  products: 4,
  inventory: 3,
  accounting: 5,
  banking: 4,
  invoicing: 4,
  deliveryNotes: 3,
  purchasing: 4,
  advancedInventory: 5,
  pricing: 4,
  payroll: 5,
  projects: 4,
  communications: 3,
  security: 4,
  reports: 3,
  data: 4,
  monitoring: 2,
  companyProfile: 3,
  tax: 3,
  budget: 3,
  claims: 3,
  crm: 4,
  alerts: 2,
  branches: 3,
  warranties: 3,
  loyalty: 3,
};
